/**
 * Pull Contentful entries → generate src/data/*.ts
 * Run: npx tsx scripts/contentful-pull.ts
 * Requiere: CONTENTFUL_DELIVERY_ACCESS_TOKEN en .env.local
 */
import { createClient } from 'contentful'
import { config } from 'dotenv'
import { writeFileSync, mkdirSync } from 'fs'
import { resolve } from 'path'

config({ path: resolve('.env.local') })

const client = createClient({
    space: process.env.CONTENTFUL_SPACE_ID!,
    accessToken: process.env.CONTENTFUL_DELIVERY_ACCESS_TOKEN!,
    environment: process.env.CONTENTFUL_ENVIRONMENT ?? 'master',
})

function val(fields: Record<string, unknown>, key: string): string {
    return String(fields[key] ?? '')
}

function arr(fields: Record<string, unknown>, key: string): string[] {
    const v = fields[key]
    return Array.isArray(v) ? v.map(String) : []
}

const header = '// Generated by scripts/contentful-pull.ts — do not edit manually\n\n'

// ─── Services ─────────────────────────────────────────────────────────────────

async function pullServices() {
    const entries = await client.getEntries({
        content_type: 'service',
        order: ['fields.order'],
        limit: 100,
    })
    const items = entries.items.map((e) => {
        const f = e.fields
        return {
            id: `${e.sys.id}`,
            eyebrow: val(f, 'eyebrow'),
            title: val(f, 'title'),
            description: val(f, 'description'),
            tags: arr(f, 'tags'),
        }
    })

    const content = `${header}import type { Service } from '@/types/service'\n
export const services: Service[] = ${JSON.stringify(items, null, 2)}\n`

    const dir = resolve('src/data')
    mkdirSync(dir, { recursive: true })
    writeFileSync(resolve(dir, 'services.ts'), content)
    console.log(`  ✓ services.ts (${items.length} entries)`)
}

// ─── Projects ─────────────────────────────────────────────────────────────────

async function pullProjects() {
    const entries = await client.getEntries({
        content_type: 'project',
        order: ['fields.order'],
        limit: 100,
    })
    const items = entries.items.map((e) => {
        const f = e.fields
        return {
            id: e.sys.id,
            title: val(f, 'title'),
            category: val(f, 'category'),
            description: val(f, 'description'),
            stack: arr(f, 'stack'),
            status: val(f, 'status') as 'activo' | 'en desarrollo' | 'completado',
            href: val(f, 'repoUrl') || undefined,
        }
    })

    const content = `${header}import type { Project } from '@/types/project'\n
export const projects: Project[] = ${JSON.stringify(items, null, 2)}\n`

    writeFileSync(resolve('src/data/projects.ts'), content)
    console.log(`  ✓ projects.ts (${items.length} entries)`)
}

// ─── Stats ────────────────────────────────────────────────────────────────────

async function pullStats() {
    const entries = await client.getEntries({
        content_type: 'stat',
        order: ['fields.order'],
        limit: 20,
    })
    const items = entries.items.map((e) => {
        const f = e.fields
        return {
            value: val(f, 'value'),
            label: val(f, 'label'),
        }
    })

    const content = `${header}export interface Stat {
  value: string
  label: string
}

export const stats: Stat[] = ${JSON.stringify(items, null, 2)}\n`

    writeFileSync(resolve('src/data/stats.ts'), content)
    console.log(`  ✓ stats.ts (${items.length} entries)`)
}

// ─── Main ─────────────────────────────────────────────────────────────────────

async function main() {
    console.log('Pulling from Contentful...\n')
    await Promise.all([pullServices(), pullProjects(), pullStats()])
    console.log('\nDone.')
}

main().catch((e) => {
    console.error('Error:', e.message)
    process.exit(1)
})
