// Generated by scripts/contentful-pull.ts — do not edit manually

import type { Service } from '@/types/service'

export const services: Service[] = [
    {
        id: 'lw7pln0EQP7zYhjI6q8lf',
        eyebrow: '01',
        title: 'Automatización de procesos',
        description:
            '¿Tienes procesos que solo tú sabes hacer y te consumen horas cada día? Automatizamos tareas repetitivas — desde seguimiento de clientes hasta generación de reportes — para que tu negocio funcione sin depender de tu tiempo.',
        tags: ['A tu medida', 'Sin mensualidad', 'Escalable'],
    },
    {
        id: '6p41EkhDzdw0dfOrRLq0gM',
        eyebrow: '02',
        title: 'CRM y gestión de clientes',
        description:
            '¿Tus clientes se pierden entre WhatsApp, correos y llamadas? Implementamos Chatwoot — un CRM open source que unifica toda tu comunicación en un solo lugar. Con tableros Kanban para seguimiento de ventas, etiquetado automático y sin pagar por usuario.',
        tags: ['Chatwoot', 'Kanban', 'WhatsApp Business', 'Open Source'],
    },
    {
        id: '5Wb5uZmgc1nJqSut43ehZD',
        eyebrow: '03',
        title: 'Sistemas propios',
        description:
            '¿Pagas mensualidades que suben cada año por software que ni usas completo? Construimos herramientas a medida que corren en infraestructura propia: sin suscripciones sorpresa, sin límites artificiales. El sistema es tuyo.',
        tags: ['Sin suscripción', 'Docker', 'Self-hosted', 'Tuyo'],
    },
    {
        id: '3ellTWZkKfp4CYMGq8JU00',
        eyebrow: '04',
        title: 'Desarrollo web que convierte',
        description:
            'Tu sitio actual existe pero no te trae clientes. Diseñamos páginas que aparecen en Google, conectan con WhatsApp y están pensadas para que quien te busque termine escribiéndote. Sin plantillas genéricas, sin mensualidades de plataforma.',
        tags: ['SEO', 'WhatsApp', 'Google Business', 'Propio'],
    },
]
