// Generated by scripts/contentful-pull.ts — do not edit manually

export interface Stat {
  value: string
  label: string
}

export const stats: Stat[] = [
  {
    "value": "5",
    "label": "Proyectos activos con CI/CD y documentación"
  },
  {
    "value": "629K",
    "label": "Líneas de código en producción"
  },
  {
    "value": "236",
    "label": "Archivos organizados en pipelines y APIs"
  },
  {
    "value": "228",
    "label": "Commits con propósito, no relleno"
  }
]
